services:
  - mysql

variables:
  MYSQL_DATABASE: "chessgame"
  MYSQL_ROOT_PASSWORD: "example"

stages:
  - connect
  - build

connect-code-job:
  stage: connect
  image: mysql
  script:
    - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"

build-code-job:
  stage: build
  image: python:3
  script:
    - echo "Lancement de l'application"
    - apt-get update -qy
    - apt-get install -qq git
    - pip install -r requirements.txt
    - sleep 120
    - bash script.sh
