services:
  - mysql

variables:
  MYSQL_DATABASE: "chessgame"
  MYSQL_ROOT_PASSWORD: "example"
  MYSQL_USER: "benji"
  MYSQL_PASSWORD: "benji"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  PASSWORD: $PASSWORD
stages:
  - test
  - build
  - deploy

test-code-job:
  stage: test
  image: python:3
  script:
    - python -m unittest test.testMychess

build-code-job:
  stage: build
  image: python:3
  script:
    - echo "Lancement de l'application"
    - apt-get update -qy
    - apt-get install -qq git
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - bash script.sh

deploy-code-job:
  stage: deploy
  image: ictu/sshpass
  script:
    - echo "Welcome to ChessGame"
    - sshpass -p $PASSWORD ssh -oStrictHostKeyChecking=no -tt benji@projetinfra.ddns.net "cd ../.. ; cd /var/ProjetInfra/chessgame ; sudo git pull ; sudo pip3 install -r requirements.txt ; sudo docker compose up -d ; sleep 20 ; sudo systemctl start server.service ; exit"
