services:
  - mysql

variables:
  MYSQL_DATABASE: "chessgame"
  MYSQL_ROOT_PASSWORD: "example"
  MYSQL_USER: "benji"
  MYSQL_PASSWORD: "benji"
  MYSQL_HOST: "localhost"
  MYSQL_PORT: "3306"

stages:
  - connect
  - build

connect-code-job:
  stage: connect
  image: mysql
  script:
    - echo "SELECT 'OK';" | mysql --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" --host="$MYSQL_HOST" --port="$MYSQL_PORT" "$MYSQL_DATABASE"

build-code-job:
  stage: build
  image: python:3
  script:
    - echo "Lancement de l'application"
    - apt-get update -qy
    - apt-get install -qq git
    - pip install -r requirements.txt
    - sleep 60
    - bash script.sh
