image: python:3

stages:
  - build
  - deploy

build-code-job:
  stage: build
  script:
    - echo "Lancement de l'application"
    - apt-get update -qy
    - apt-get install -qq git
    - pip install -r requirements.txt
    - bash script.sh

deploy-code-job:
  stage: deploy
  script:
    - echo "Déploiement de l'application"
